backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
    - name: "tours"
    label: "Tours"
    files:
            - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
                    - {label: "Body", name: "body", widget: "code"}
